sonar.organization=shift-left-happens
sonar.projectKey=shift-left-happens_fake_info_backend
sonar.sources=src/,index.php
sonar.language=php
sonar.php.version=8.2
sonar.exclusions=vendor/**,data/**,db/**
